config/routes.rb
Gfw::Application.routes.draw do

  # For authentication and logging in
  services = %w[twitter google facebook ~]
  # For services that orgs can't overwrige
  administrative = %w[users authentications assets]
  
  match '/auth/:provider/callback' => 'authentications#create', :constraints => lambda{|req| services.include?(req.params[:provider]) },  :as => 'new_auth'
  resources :authentications
  devise_for :users, :controllers => { :registrations => 'registrations'}
  
  # If logged in will take to org index, otherwise home page
  root :to => "home#index", :constraints => lambda{|req| req.session['warden.user.user.key'].blank?}
  root :to => "org#index", :constraints => lambda{|req| !req.session['warden.user.user.key'].blank?}
  match '/notice' => "home#notice", :as => 'notice'
  
  # Allows for discrete and non-discrete linking to orgs
  match '/:org_id' => 'org#show', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'org_discrete'
  match '/:org_name' => 'org#show', :constraints => lambda{|req| !administrative.include?(req.params[:org_name]) }, :as => 'org'

  # Membership management routes
  match '/:org_id/~/:membership/destroy' => 'memberships#destroy', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'destroy_membership'
  match '/:org_id/~/:membership/update' => 'memberships#update', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'update_membership'
  match '/:org_id/~/invite/create' => 'memberships#add', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'add_membership'
  match '/:org_id/~/invite/:invite_token' => 'memberships#invite', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'invite_membership'

  #List management routes
  match '/:org_id/~/create' => 'lists#create', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'list_create', :via => [:put, :post]
  match '/:org_id/~/new' => 'lists#new', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'list_new'

  match '/:org_name/:list_name/update' => 'lists#update', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name]) }, :as => 'list_update', :via => [:put, :post]
  match '/:org_name/:list_name/~edit' => 'lists#edit', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name]) }, :as => 'list_edit'
  match '/:org_name/:list_name/~edit/update' => 'lists#update_list', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name]) }, :as => 'list_admin_update', :via => [:put, :post]
  match '/:org_name/:list_name' => 'lists#show', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name])}, :as => 'list'
  
  #Views with list
  match '/:org_name/:list_name/:view_name' => 'lists#show', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name])}, :as => 'view'
  match '/:org_id/:list_id/:view_slug' => 'lists#show', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id] && /^[-+]?[0-9]+$/ === req.params[:list_id] }, :as => 'view_discrete'
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  @to_include = [:items, :views]
  
  
  def new
    @org = Org.find(params[:org_id])
    authorize! :manage, @org, :alert => 'NO, you can\'t do that!'
    
    @list = @org.lists.new
    
    respond_to do |format|
      format.html # new.html.erb
    end
    
  end
  
  def create
    @org = Org.find(params[:org_id])
    
    authorize! :manage, @org, :alert => 'NO, you can\'t do that!'
    
    @list = @org.lists.new( params[:list] )
    
    if @list.save
      @msg = 'Yessss list '+@list.name.capitalize+' was created. NOW MAKE SOMETHING OF IT'
      redirect_to list_edit_path( @org.to_param, @list.to_param ), :notice =>  @msg
    else
      @msg = '#fail cause '+@list.errors.map{ |k,v| k.to_s.capitalize+' '+v }.join(',')
      redirect_to list_new_path( @org.id ), :alert =>  @msg
    end
    
  end
  
  def edit
    org = Org.find_by_slug(params[:org_name]).id
    @list = List.find_by_org_and_slug(org, params[:list_name])
    authorize! :manage, @list.org, :alert => 'You don\'t have access to that List'

    @fields = @list.fields
    unless @list.operators.nil?  
      unless @list.operators[:order].nil?
        new_fields = []
        order = @list.operators[:order].class == String ? @list.operators[:order].split(' ') : @list.operators[:order]
        order.each do |o|
          int = o.class == String ? o.to_i : o
          pos = @fields.index{ |f| f.id == int }
          new_fields.push( @fields.slice(pos) ) unless pos.nil?
        end
        @fields = new_fields.concat( @fields.select{ |f| @list.operators[:order].index(f.id).nil? } )
        @fields = @fields.uniq
      end
    end

    respond_to do |format|
      format.html # show.html.erb
    end

  end

  def update_list
    org = Org.find_by_slug(params[:org_name]).id
    @list = List.find_by_org_and_slug(org, params[:list_name])
    authorize! :manage, @list.org, :alert => 'You don\'t have access to that List'

    fields = params[:fields]
    response = { :fields => [], :list => {} }
    
    fields.each do |field_posted|
      field_post = field_posted[1]
      temp_id =  field_post['id'].class == Float ? field_post['id'].to_s.index('new_') : field_post['id'].index('new_')
      
      if temp_id.nil?
        field = @list.fields.find(field_post['id'])
        if field.nil?
          response[:fields].push( {:success => false, :id => field.id, :name => field.name} )
        else
          if field_post['_destroy'].nil?
            success = field.update_attributes(field_post)
            response[:fields].push( {:success => success, :id => field.id, :name => field.name} )
          else
            success = field.delete
            response[:fields].push( {:success => success, :id => field.id, :destroy => true } )
          end
        end
      else
        field = @list.fields.new( field_post )
        success = field.save
        response[:fields].push( {:success => success, :temp_id => field_post['id'], :id => field.id, :name => field.name, :error => field.errors } )
      end
      
    end

    computables = []
    fucked_computables = params['computables']
    fucked_computables.each do |fucked_computable|
      computable = {}
      computable[:field] = fucked_computable[1]['field']
      computable[:operations] = []
      fucked_computable[1]['operations']['0'].each do |fucked_operation|
        operation = {}
        operation[:report] = fucked_operation[1]['report']
        operation[:label] = fucked_operation[1]['label']
        computable[:operations].push(operation )
      end
      computables.push(computable)
    end

    @list.operators = { 
      :order => params['order'], 
      :groupables => params['groupables'], 
      :computables => computables
    }
    response[:list] = {:success => @list.save }
    
    render :json => response, :callback  => params['callback']
    
  end
  
  def show
    
    if params[:list_name].nil?
      @list = List.find(params[:list_id], :include => @to_include )
    else
      org = Org.find_by_slug(params[:org_name]).id
      @list = List.find_by_org_and_slug(org, params[:list_name], :include => @to_include )
    end
    
    authorize! :show, @list.org, :alert => 'You don\'t have access to that List'
    

    @current_view = @list.views.index{|v| v.to_param == params[:view_name] || v.slug == params[:view_slug] }
    @fields = @list.fields
    @query = @list.rows()
    @rows = @query[:rows]
    @size = @query[:size]
    @views = @list.views

    unless @list.operators.nil?  
      unless @list.operators[:order].nil?
        new_fields = []
        order = @list.operators[:order].class == String ? @list.operators[:order].split(' ') : @list.operators[:order]
        order.each do |o|
          int = o.class == String ? o.to_i : o
          pos = @fields.index{ |f| f.id == int }
          new_fields.push( @fields.slice(pos) ) unless pos.nil?
        end
        @fields = new_fields.concat( @fields.select{ |f| @list.operators[:order].index(f.id).nil? } )
        @fields = @fields.uniq
      end
    end
    
    #TODO: Add some sort of paging function when querying rows via a sort
    authorize! :show, @list.org, :alert => 'You don\'t have access to that List'

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rows }
      format.xls do
          render :xls => @rows,
                         :columns => @fields.map{ |f| f.to_param },
                         :headers => @fields.map{ |f| f.name }
        end
      
    end

  end
  
  def update

    org = Org.find_by_slug(params[:org_name]).id
    @list = List.find_by_org_and_slug(org, params[:list_name], :include => @to_include )
    @rows_results = []
    @views_results = []
    
    authorize! :show, @list.org, :alert => 'You don\'t have access to that List'
    begin
      params[:rows] = params[:rows].class == String ? JSON.parse(params[:rows]) : params[:rows]
      unless params[:rows].nil? || params[:rows].empty? 
          @rows = params[:rows].to_a
          @rows.each do |a|
            r = a[1]
            r[:list] = @list
            begin
              # TO DO: Add something to authorize each row save, right now could sneak in in data in the row data using different list names
              # IDEAS: pass the authorized org into the save method ? and check the @list.org == @list.org on save to verify no funny business
              @rows_results.push( Row.new(r).save )
            rescue
               @error = {}
               @error[:key] = r['key'] || r[:key]
               @error[:e_data] = r
               @error[:success] = false
               @error[:error] = ['Error on Row save']
               @rows_results.push( @error )
             end
          end
      end
    rescue
      @rows_results = {:success => false, :error => 'Invalid JSON for rows' }
    end 
    
    unless params[:views].nil? || params[:views].empty?
      begin
        params[:views] = params[:views].class == String ? JSON.parse(params[:views]) : params[:views]
        @views = params[:views].to_a

        @views.each do |a|
          v = a[1]
          begin
            unless v['_destroy'].nil?
              @view = View.find_by_id_and_list_id(v['id'], @list.id)
              @view.delete
              @views_results.push( {:id => @view.id, :success => true, :_destroy => true, :name => @view.name } )
            else
              if v['id'] == 'new' || v['id'].nil?
                v['id'] = nil
                @view = @list.views.new(v)
                success = @view.save
              else
                ['sorts','filters','groups','columns','maps'].each do |array|
                  v[array] = [] if v[array].nil?
                end
                @view = View.find_by_id_and_list_id(v['id'], @list.id)
                success = @view.update_attributes(v)
              end
              @views_results.push( {:id => @view.id, :success => success, :name => @view.name, :slug => @view.slug, :data => @view } )
            end
          rescue
            @error = {}
            @error[:id] = v['id'] || v[:id]
            @error[:e_data] = v
            @error[:success] = false
            @error[:error] = ['Error on View save']
            @views_results.push( @error )
          end
        end
      rescue
        @views_results = {:success => false, :error => 'Invalid JSON for views' }
      end
      
    end
    
    
    respond_to do |format|
      format.json { render json: {:rows => @rows_results, :views => @views_results, :sent => @rows } }
    end

  end


end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_analyze.html.erb
<div class="view_title" data-bind="with: dataModel.current.view">
	<h2 class="view_title" data-bind="text: $data.name, css: {'unsaved' : views.indexOf($data) === -1 }"></h2>
	<div class="section">
		<h3>Constrain</h3>
		<em>Limit what you're looking at</em>
		<div data-bind="template: {name: 'filter', foreach: $data.filters }"></div>
		<span class="add clickable add_filter">+Add</span>
	</div>
	<div class="section">
		<h3>Tabulate</h3>
		<em>Group &amp; pivot your data</em>
		<div data-bind="template: {name: 'grouped', foreach: $data.groupings }">
			<div style="clear:both;"></div>
		</div>
		<span class="add clickable add_grouping">+Add</span>
	</div>
	<div class="section">
		<h3>Plan</h3>
		<em>Create a plan, make it happen</em>
		<div data-bind="template: {name: 'goal', foreach: $data.goals }">
			<div style="clear:both;"></div>
		</div>
		<span class="add clickable add_goal">+Add</span>
	</div>
	<div class="section">
		<h3>Map</h3>
		<em>Your data on the world</em>
		<div data-bind="foreach: $data.maps ">
			<div class="map">
				<span class="remove clickable">remove</span>
				<div class="map_container" data-bind="gfMap: $data.map "></div>
				<div class="map_menu">
					<label>Field to Map:</label> <select data-bind="value: $data.field, options: fields.locations, optionsText: 'name' "></select>
				</div>
			</div>
		</div>
		<span class="add clickable add_map">+Add</span>
	</div>

<!--

	<div class="section">
		<h3>Cloud</h3>
		<em>Your data's word cloud</em>
		<span class="add clickable">+Add</span>
	</div>

	<div class="section">
		<h3>Calendar</h3>
		<em>Your data on time</em>
		<span class="add clickable">+Add</span>
	</div>
-->
</div>

app/views/lists/_bug.html.erb
<div id="bug_overlay" >
	<p><strong>LET'S KILL IT!</strong></p>
	<p>Maybe you just don't like my hat. More likely, something's gone terribly wrong.</p>
	<p>Pull up a <span style="text-decoration: line-through;">chair</span> form and tell me your troubles.</p>
	<form id="bug_form">
		<label>Your Email</label>
		<input type="text" id="email" value="<%= current_user.email unless current_user.nil? %>">
		<label>Your Beef</label>
		<textarea id="bug_msg"></textarea>
		<input type="hidden" value="<%= current_user.id unless current_user.nil? %>" id="current_user">
		<input type="hidden" value="<%= session %>" id="session_data">
		<input type="submit" value="talk to me">
	</form>
</div>

app/views/lists/edit.html.erb
<% content_for :extra do %>
	<span class="save make_save clickable">save</span>
<% end %>



<div id="edit_list">

	<h1>Edit <%= @list.name %></h1>
	<h2><%= link_to 'View List', list_path(@list.org.to_param, @list.to_param) %></h1>

	<div data-bind="sortable: {data: editModel.fields, allowDrop: false} ">
		<div class="field" data-bind=" css: { disabled: $data.disabled, error: $data.error }">
			<p class="locked" data-bind="visible: $data.disabled"> <strong>LOCKED</strong> You cannot edit</p>
			<div class="drag">
				<div class="top_arrow arrow"></div>
				drag<br />
				to<br />
				reorder
				<div class="base_arrow arrow"></div>
			</div>
			<span class="clickable remove delete_field">Delete</span>
			<div class="field_options">
				<span class="error">You Need a New Name</span>
				<h3 class="name" >
					Field Name: <input type="text" data-bind="valueUpdate: 'afterkeydown', value: $data.name, disable: $data.disabled"> 
				</h3>
				<h3>Type: <select data-bind="options: $parent.types(), value: $data.type, disable: $data.disabled"></select></h3>
				<p data-bind="text: editModel.all_types[ $data.type() ] "></p>
			</div>
			<div class="field_options_options" data-bind="if: $data.type() == 'select' || $data.type() == 'multiselect' ">
				<h3>Field Options</h3>
				<ul data-bind="sortable: { data: $data.options, isEnabled: $data.disabled, allowDrop: false }">
					<li><input type="text" data-bind="valueUpdate: 'afterkeydown', value: $data.name, disable: $parent.disabled"> <span data-bind="visible: !$parent.disabled"><span class="clickable remove delete_option">(x)</span></span></li>
				</ul>
				<span class="clickable add_option" data-bind="visible: !$data.disabled">+Add</span>
			</div>
			<div class="anaylsis">
				<h2 class=" show_options">Analysis Options</h2>
				<div class="groupable">
					<p><strong>Groupable: </strong><input type="checkbox" data-bind="checked: $data.groupable"> <em>Can this row be grouped?</em></p>
				</div>
				<div class="computables">
					<h3>Computable</h3>
					<p>How should we analyze this field?</p>
						<ul data-bind="foreach: $data.computables" >
							<li data-bind="css: {'disabled': !$data.enabled() }">
								<p data-bind="html: editModel.report_definitions[$data.report]"></p>
								<strong>Label:</strong><input  type="text"  data-bind="value: $data.label, disable: !$data.enabled() "><strong>Enabled:</strong><input data-bind="checked: $data.enabled" type="checkbox">
							</li>
						</ul>
				</div>
			</div>
		<div style="clear:both;"></div>
		</div>
	</div>
	<div>
		<h3 class="clickable button add_field">Add</h3>
	</div>


<script type="text/javascript" charset="utf-8">
	var _fields = <%= raw @fields.each{ |f| f['disabled'] = true if f.list_id != @list.id }.to_json %>,
		_operators = <%= raw @list.operators.to_json %> == null ? [] : <%= raw @list.operators.to_json %>
		editModel = {
			fields: ko.observableArray([]),
			operatirs: ko.computed( function() {
				return ''
			}, this),
			all_types: { 
				'text': 'For small amounts of text',
				'suggest': 'For a small amounts of text, with suggestions based on what was previously entered',
				'number': 'For numbers, can + or -',
				'block': 'For paragraphic text',
				'date': 'For dates',
				'select': 'For some option, can pick one',
				'multiselect': 'For some options, can pick many',
				'array': 'For a list of things that can be clicked on',
				'user': 'Records the username of the person who created that row',
				'location' : 'For things like addresses, will attempt to assign a Lat / Long to whatever you enter'
			},
			types: function() {
				var all_types = []
				for( var i in editModel.all_types ) all_types.push(i)
				return all_types
			},
			report_definitions: {
				'count' : '<em>Count</em> reports on the number of things there are in a particular grouping. A, 1, 2, 3, A is five things, according to count',
				'unique' : '<em>Average</em> reports on the number of things there are in a particular grouping. A, 1, 2, 1, A is three things, according to unique',
				'sum' : '<em>Sum</em> reports on the sum of things there are in a particular grouping, ignores non-numbers',
				'average' : '<em>Average</em> reports on the average of things there are in a particular grouping, ignores non-numbers',
				'max' : '<em>Maximum</em> reports on the largest number of things there are in a particular grouping, ignores non-numbers',
				'min' : '<em>Minimum</em> reports on the smallest number of things there are in a particular grouping, ignores non-numbers'
			}
		}

	assign_computables = function(field, computables) {
		var all_on = typeof computables == 'undefined',
			type = field.field_type || 'text'
			options = []
		
		switch(type) {
			case 'number': 
				options.push( new Object({label: ko.observable('sum'), report: 'sum', enabled: ko.observable( all_on ) }) );
				options.push( new Object({label: ko.observable('avg'), report: 'average', enabled: ko.observable( all_on ) }) );
				options.push( new Object({label: ko.observable('max'), report: 'max', enabled: ko.observable( all_on ) }) );
				options.push( new Object({label: ko.observable('min'), report: 'min', enabled: ko.observable( all_on ) }) );
				break;
			default:
				options.push( new Object({label: ko.observable('count'), report: 'count', enabled: ko.observable( all_on )}) );
				options.push( new Object({label: ko.observable('unique'), report: 'unique', enabled: ko.observable( all_on ) }) );
				break;
		}
		if( !all_on && typeof field.name != 'undefined' ) {
			var this_field = computables.filter( function(el) { return el.field == field.name.replace(/ /g,'_') })[0]
				for (var i=0; i < options.length; i++) {
					var this_option = typeof this_field != 'undefined' ? this_field.operations.filter( function(el) { return el.report == options[i].report }) : []
					if( this_option.length > 0 ) {

						options[i].label( this_option[0].label )
						options[i].enabled( true )
					}
				};
		}
		return options;
	}

	for (var i=0; i < _fields.length; i++) editModel.fields.push({
			name: ko.observable(_fields[i].name),
			id: _fields[i].id,
			type: ko.observable(_fields[i].field_type), 
			options: ko.observableArray( _fields[i].field_options == 'null' || _fields[i].field_options == null  ? [] : _fields[i].field_options.map( function(el) { return { name: ko.observable(el) } } ) ),
			groupable: ko.observable( typeof _operators['groupables'] == 'undefined' || _operators == null  || _operators['groupables'].indexOf( _fields[0].name.replace(/ /g,'_') ) !== -1 ),
			computables: assign_computables(_fields[i], _operators == 'null' ? [] : _operators.computables),
			disabled: _fields[i].disabled,
			error: ko.observable('')
		})
	
	editModel.saving = ko.computed( function() {
		var order = [],
			computables = [],
			groupables = [],
			save_fields = []
			fields = ko.toJS(editModel.fields )
		
		for (var i=0; i < fields.length; i++) {
			var field = fields[i], post_field = {}
			if( field.groupable ) groupables.push( field.name.replace(/ /g,'_') )
			if( field.id != null ) order.push( field.id )
	
			var active_computables = field.computables.filter( function(el) { return el.enabled })
			if( active_computables.length > 0 ) {
				computables.push( {
					field: field.name.replace(/ /g,'_'), 
					operations: [ active_computables.map( function(el) { el.enabled = null; return el }) ] 
				})
			}
	
			if( !field.disabled ) {
				post_field.field_type = field.type
				post_field.field_options = editModel.fields()[i].options().map( function(el) { return ko.toJS( el.name() ) } );
				console.log( post_field.field_options )
				post_field.id = field.id
				post_field.name = field.name	
				save_fields.push( post_field )
			}

		}
		return {fields: save_fields, order: order, computables: computables, groupables: groupables }
	})

	$(document)
		.on('click','.add_field',function(e) {
			editModel.fields.push({
				name: ko.observable( 'New Field' ),
				id: 'new_'+Math.floor(Math.random()*1000),
				type: ko.observable('Text'), 
				options: ko.observableArray([]),
				groupable: ko.observable( true ),
				computables: assign_computables( {}, _operators == null ? [] : _operators.computables),
				error: ko.observable('')
			})
		})
		.on('click','.delete_field',function(e) {
			var ctx = ko.contextFor(this)
			if( ctx.$data.id.toString().search('new_') === -1 ) ctx.$parent.fields.destroy( ctx.$data )
			else ctx.$parent.fields.remove( ctx.$data )
		})
		.on('click','.add_option',function(e) {
			var ctx = ko.contextFor(this)
			ctx.$data.options.push( {name: ko.observable('New Option') } )
		})
		.on('click','.delete_option',function(e) {
			var ctx = ko.contextFor(this)
			ctx.$parent.options.remove( ctx.$data)
		})
		.on('click','.show_options',function(e){
			$('.groupable, .computables',$(this).parent()).slideToggle()()
		})
		.on('click','.make_save',function(e){
			$this = $(this).removeClass('make_save').removeClass('clickable').text('saving...')
			$.post(
				'<%= list_admin_update_path(@list.org.to_param, @list.to_param) %>',
				editModel.saving(),
				function(response) {
					for (var i=0; i < response.fields.length; i++) {
						var returned_field = response.fields[i], field = null
						if( typeof returned_field.temp_id != 'undefined') {
							field = editModel.fields().filter( function(el) { return el.id == returned_field.temp_id })[0]
						} else {
							field = editModel.fields().filter( function(el) { return el.id == returned_field.id })[0]
						}
						if( typeof returned_field._destroy != 'undefined') editModel.fields.remove(field)
						else {
							if( returned_field.success ) {
								field.id = returned_field.id
								field.name( returned_field.name )
							} else {
								field.error( true ) 
							}
						}
						$this.addClass('make_save').addClass('clickable').text('save')
					};
					
				})
		})
		.ready( function() {  
			ko.applyBindings(editModel);
		})
</script>


</div>

app/views/lists/new.html.erb
<div id="create_list">
	<h2>New List</h2>

	<%= form_for @list, :url => list_create_path(@org.id) do |f| %>

		<h3><%= f.label :name %> <%= f.text_field :name %></h3>
	 	<p>This is the name of your list. It cannot have the same name as any other list in your org. You cannot change this again, so do not screw it up.</p>
	  <h3><%= f.label :parent_id %> <%= f.select(:parent_id, current_user.orgs.map{ |o|  o.lists  }.flatten().collect {|p| [ p.org.name+': '+p.name, p.id ] } ,  {:prompt => '-- Optional: Select Parent List'}) %></h3>
		<p>Lists can have <em>parents</em>. If a list has a <em>parent</em>, they inherit all of their <em>parent's</em> fields. Any row created on a child list flows upward, so the parent gets anything the child creates, but only for parent's fields.</p>
		<h3 class="clickable" onclick="$(this).next('div').slideToggle()">Still Confused?</h3>
		<div class="explain">
			<p>Because this is confusing, I've provided a helpful example of two lists: <strong>Mufasa</strong> and <strong>Simba</strong></p>
			<p><strong>Mufasa</strong> has the following structure:</p>
			<table>
				<tr>
					<th></th>
					<th>Pride Name</th>
					<th>Lions in Pride</th>
					<th>Hyena Kills</th>
				</tr>
				<tr>
					<td>1</td>
					<td>Awesome Pride</td>
					<td>3</td>
					<td>20</td>
				</tr>
				<tr>
					<td>2</td>
					<td>Pride Pride</td>
					<td>3</td>
					<td>20</td>
				</tr>
			</table>
			<p>Now if we create a child list, called <b>Simba</b> it will inherit all of the fields from it's parent, <strong>Mufasa</strong></p>
			<table>
				<tr>
					<th>Pride Name</th>
					<th>Lions in Pride</th>
					<th>Hyena Kills</th>
				</tr>
			</table>
			<p>And now we add some fields to <strong>Simba</strong> and create a new row</p>
			<table>
				<tr>
					<th></th>
					<th>Pride Name</th>
					<th>Lions in Pride</th>
					<th>Hyena Kills</th>
					<th>Bugs Eaten</th>
					<th>Date of Last Song Sung</th>
				</tr>
				<tr>
					<td>1</td>
					<td>Outkast Pride</td>
					<td>4</td>
					<td>0</td>
					<td>300</td>
					<td>June 15, 1994</td>
				</tr>
			</table>
			<p>It will create a new row in on <strong>Mufasa</strong> but ONLY with the fields from <strong>Mufasa</strong></p>
			<table>
				<tr>
					<th></th>
					<th>Pride Name</th>
					<th>Lions in Pride</th>
					<th>Hyena Kills</th>
				</tr>
				<tr>
					<td>1</td>
					<td>Awesome Pride</td>
					<td>3</td>
					<td>20</td>
				</tr>
				<tr>
					<td>2</td>
					<td>Pride Pride</td>
					<td>3</td>
					<td>20</td>
				</tr>
				<tr>
					<td>3</td>
					<td>Outkast Pride</td>
					<td>4</td>
					<td>0</td>
				</tr>
			</table>
			<p>Lists can only have only one parent and can have multiple children, and there can be multiple generations of lists (parent > child > grand child)</p>
			<h3 ><a style="color: yellow" onclick="$(this).parents('div.explain').slideToggle()" href="http://www.youtube.com/watch?v=xB5ceAruYrI" target="_blank">Got it!</a> ... or <a style="color: yellow" onclick="$(this).parents('div.explain').slideToggle()" href="http://www.youtube.com/watch?v=vX07j9SDFcc" target="_blank">Still Confused?</a></h3>
		</div>
	  <div class="actions">
	    <%= f.submit %>
	  </div>
	<% end %>
</div>