config/routes.rb
Gfw::Application.routes.draw do

  # For authentication and logging in
  services = %w[twitter google facebook ~]
  # For services that orgs can't overwrige
  administrative = %w[users authentications assets]
  
  match '/auth/:provider/callback' => 'authentications#create', :constraints => lambda{|req| services.include?(req.params[:provider]) },  :as => 'new_auth'
  resources :authentications
  devise_for :users, :controllers => { :registrations => 'registrations'}
  
  # If logged in will take to org index, otherwise home page
  root :to => "home#index", :constraints => lambda{|req| req.session['warden.user.user.key'].blank?}
  root :to => "org#index", :constraints => lambda{|req| !req.session['warden.user.user.key'].blank?}
  match '/notice' => "home#notice", :as => 'notice'
  
  # Allows for discrete and non-discrete linking to orgs
  match '/:org_id' => 'org#show', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'org_discrete'
  match '/:org_name' => 'org#show', :constraints => lambda{|req| !administrative.include?(req.params[:org_name]) }, :as => 'org'

  # Membership management routes
  match '/:org_id/~/:membership/destroy' => 'memberships#destroy', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'destroy_membership'
  match '/:org_id/~/:membership/update' => 'memberships#update', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'update_membership'
  match '/:org_id/~/invite/create' => 'memberships#add', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'add_membership'
  match '/:org_id/~/invite/:invite_token' => 'memberships#invite', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'invite_membership'

  #List management routes
  match '/:org_id/~/create' => 'lists#create', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'list_create', :via => [:put, :post]
  match '/:org_id/~/new' => 'lists#new', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'list_new'

  match '/:org_name/:list_name/update' => 'lists#update', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name]) }, :as => 'list_update', :via => [:put, :post]
  match '/:org_name/:list_name/~edit' => 'lists#edit', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name]) }, :as => 'list_edit'
  match '/:org_name/:list_name/~edit/update' => 'lists#update_list', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name]) }, :as => 'list_admin_update', :via => [:put, :post]
  match '/:org_name/:list_name' => 'lists#show', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name])}, :as => 'list'
  
  #Views with list
  match '/:org_name/:list_name/:view_name' => 'lists#show', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name])}, :as => 'view'
  match '/:org_id/:list_id/:view_slug' => 'lists#show', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id] && /^[-+]?[0-9]+$/ === req.params[:list_id] }, :as => 'view_discrete'
  
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController

  # GET /authentications
  # GET /authentications.json
  
  def index
    @authentications = current_user.authentications if current_user
  end
  
  def create
    omniauth = request.env["omniauth.auth"].except('extra')
    authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    if authentication && authentication.user.present?
      sign_in_and_redirect(:user, authentication.user)
    elsif current_user
      current_user.authentications.create(:provider => omniauth ['provider'], :uid => omniauth['uid'])
      flash[:notice] = "Authentication successful."
      redirect_to authentications_url
    else 
      user = User.new
      user.apply_omniauth(omniauth)
      if user.save
        flash[:notice] = "Signed in successfully."
        sign_in_and_redirect(:user, user)
      else
        session[:omniauth] = omniauth
        redirect_to new_user_registration_url
      end
    end
  end
  
  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_url
  end
  
  protected
  
  def handle_unverified_request
    true
  end
  

end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/_form.html.erb
<%= form_for(@authentication) do |f| %>
  <% if @authentication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authentication.errors.count, "error") %> prohibited this authentication from being saved:</h2>

      <ul>
      <% @authentication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authentications/_links.erb
<ul>
	<li><a href="/auth/twitter" class="auth_provider">Twitter</a></li>
	<li><a href="/auth/facebook" class="auth_provider">Facebook</a></li>
	<li><a href="/auth/google" class="auth_provider">Google</a></li>
</ul>

app/views/authentications/edit.html.erb
<h1>Editing authentication</h1>

<%= render 'form' %>

<%= link_to 'Show', @authentication %> |
<%= link_to 'Back', authentications_path %>

app/views/authentications/index.html.erb
<% if @authentications %>
  <% unless @authentications.empty? %>
    <p><strong>You have signed in with these services:</strong></p>
    <div class="authentications">
      <% for authentication in @authentications %>
        <div class="authentication">
          <div class="provider"><%= authentication.provider %></div>
          <div class="uid"><%= authentication.uid %></div>
          <%= link_to "X", authentication, :confirm => 'Are you sure you want to remove this authentication option?', :method => :delete, :class => "remove" %>
        </div>
      <% end %>
      <div class="clear"></div>
    </div>
  <% end %>
  <p><strong>Add another service to sign in with:</strong></p>
<% else %>
  <p><strong>Sign in through one of these services:</strong></p>
<% end %>
<%= render :partial => "authentications/links" %>

<% unless user_signed_in? %>
  <p>
    <strong>Don't use these services?</strong>
    <%= link_to "Sign up", new_user_registration_path %> or
    <%= link_to "sign in", new_user_session_path %> with a password.
  </p>
<% end %>

app/views/authentications/new.html.erb
<h1>New authentication</h1>

<%= render 'form' %>

<%= link_to 'Back', authentications_path %>

app/views/authentications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @authentication.user %>
</p>

<p>
  <b>Provider:</b>
  <%= @authentication.provider %>
</p>

<p>
  <b>Token:</b>
  <%= @authentication.token %>
</p>

<p>
  <b>Uid:</b>
  <%= @authentication.uid %>
</p>


<%= link_to 'Edit', edit_authentication_path(@authentication) %> |
<%= link_to 'Back', authentications_path %>