config/routes.rb
Gfw::Application.routes.draw do

  # For authentication and logging in
  services = %w[twitter google facebook ~]
  # For services that orgs can't overwrige
  administrative = %w[users authentications assets]
  
  match '/auth/:provider/callback' => 'authentications#create', :constraints => lambda{|req| services.include?(req.params[:provider]) },  :as => 'new_auth'
  resources :authentications
  devise_for :users, :controllers => { :registrations => 'registrations'}
  
  # If logged in will take to org index, otherwise home page
  root :to => "home#index", :constraints => lambda{|req| req.session['warden.user.user.key'].blank?}
  root :to => "org#index", :constraints => lambda{|req| !req.session['warden.user.user.key'].blank?}
  match '/notice' => "home#notice", :as => 'notice'
  
  # Allows for discrete and non-discrete linking to orgs
  match '/:org_id' => 'org#show', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'org_discrete'
  match '/:org_name' => 'org#show', :constraints => lambda{|req| !administrative.include?(req.params[:org_name]) }, :as => 'org'

  # Membership management routes
  match '/:org_id/~/:membership/destroy' => 'memberships#destroy', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'destroy_membership'
  match '/:org_id/~/:membership/update' => 'memberships#update', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'update_membership'
  match '/:org_id/~/invite/create' => 'memberships#add', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'add_membership'
  match '/:org_id/~/invite/:invite_token' => 'memberships#invite', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'invite_membership'

  #List management routes
  match '/:org_id/~/create' => 'lists#create', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'list_create', :via => [:put, :post]
  match '/:org_id/~/new' => 'lists#new', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'list_new'

  match '/:org_name/:list_name/update' => 'lists#update', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name]) }, :as => 'list_update', :via => [:put, :post]
  match '/:org_name/:list_name/~edit' => 'lists#edit', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name]) }, :as => 'list_edit'
  match '/:org_name/:list_name/~edit/update' => 'lists#update_list', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name]) }, :as => 'list_admin_update', :via => [:put, :post]
  match '/:org_name/:list_name' => 'lists#show', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name])}, :as => 'list'
  
  #Views with list
  match '/:org_name/:list_name/:view_name' => 'lists#show', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name])}, :as => 'view'
  match '/:org_id/:list_id/:view_slug' => 'lists#show', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id] && /^[-+]?[0-9]+$/ === req.params[:list_id] }, :as => 'view_discrete'
  
end

app/models/org.rb
class Org < ActiveRecord::Base
  belongs_to :parent, :class_name => "Org", :foreign_key => 'parent_id'
  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships, :conditions => {:memberships => { :approved => true }}
  has_many :lists
  
  def parents
    parent = self.parent
    parents = []
    while !parent.nil?
      parents.push(parent)
      parent = parent.parent
    end
    return parents
  end
  
  
  #Stuff for the name field
  before_validation :fix_name
  validates_uniqueness_of :name
  validates_presence_of :name

  def fix_name
    self.name = self.name.split(' ').map {|w| w.capitalize }.join(' ') unless self.name.nil?
  end
  
  def to_param
    self.name.downcase.gsub(' ','_')
  end

  def self.find_smart(find, args = {} )
    if /\b\d+\b/ === find
      self.find(find, args)
    else
      self.find_by_slug(find, args)
    end
  end
    
  def self.find_by_slug(slug, args = {})
    self.find_by_name(slug.gsub('_',' ').split(' ').map {|w| w.capitalize }.join(' '), args)
  end
  

  
end

app/controllers/org_controller.rb
class OrgController < ApplicationController
  def index
    @orgs = Org.all.select{ |o| can? :read, o }
  end

  def show
    @org = Org.find_smart( params[:org_id] || params[:org_name], :include => :memberships )
    @invites = @org.memberships.select{ |m| m.approved? && m.user_id.nil? && !m.invite_token.nil? } unless @org.nil?

    authorize! :show, @org, :alert => 'You don\'t have access to that Org'
  end


end

app/helpers/org_helper.rb
module OrgHelper
end

app/views/org/index.html.erb
<% unless @orgs.empty? %>
<p>To get started, select one of your organizations.</h2>
	<ul id="org_list">
		<% @orgs.each do |o| %>
		<li>
			<%= link_to o.name, org_path(o.to_param) %>
		</li>
		<% end %>
	</ul>
<% else %>
<p>Hmm you don't seem to have any organizations. This will not be a productive visit, will it?</p>
<% end %>

app/views/org/show.html.erb
<% content_for :doc_title, @org.name %>

<% content_for :page_title do %>
	<%= @org.name %>
<% end %>


<% unless @org.lists.empty? %>
	<h2>Lists</h2>
	<ul>
		<% @org.lists.each do |list| %>
		<li>
			<%= link_to list.name, list_path(@org.to_param, list.to_param) %>
			<em><%= link_to 'Edit', list_edit_path(@org.to_param, list.to_param) if can? :manage, @org%></em>
		</li>
		<% end %>
	</ul>
<% end %>
<%= link_to 'New List', list_new_path(@org.id), :class => 'button', :style => 'padding: 6px 30px; height: 10px; margin: 0; line-height: 5em;' if can? :manage, @org %>


<% unless @org.users.empty? %>
	<h2>Users</h2>
	<ul>
		<% @org.users.each do |user| %>
		<li>
			<strong>
				<%= user.email %>
			</strong>
			<% if current_user == user %>
				 (that's you)
			<% else %>
				<% if can? :manage, @org %>
					<% if user.membership(@org).admin? %>
						<%= link_to 'remove admin?', update_membership_path(@org.id, user.membership(@org).id, :doing => 'remove-admin') %>
					<% else %>
						<%= link_to 'make admin?', update_membership_path(@org.id, user.membership(@org).id, :doing => 'make-admin') %>
					<% end %>
					<%= link_to 'remove?', destroy_membership_path( @org.id, user.membership(@org).id ) %>
				<% end %>
			<% end %>
		</li>
		<% end %>
	</ul>
<% end %>

<% if can? :manage, @org %>
<h2>Invites</h2>
<% unless @invites.empty? %>
	<ul>
		<% @invites.each do |invite| %>
			<% unless invite.invite_token.nil? %>
			<li>
				<input value="<%= root_url+invite_membership_path(@org.id, invite.invite_token).slice(1,100) %>" class="url_select">
				(<%= link_to 'x', destroy_membership_path( @org.id, invite.id ) %>)
				
			</li>
			<% end %>
		<% end %>
	</ul>
<% end %>
<%= link_to '+Make', add_membership_path(@org.id) %>
<% end %>