config/routes.rb
Gfw::Application.routes.draw do

  # For authentication and logging in
  services = %w[twitter google facebook ~]
  # For services that orgs can't overwrige
  administrative = %w[users authentications assets]
  
  match '/auth/:provider/callback' => 'authentications#create', :constraints => lambda{|req| services.include?(req.params[:provider]) },  :as => 'new_auth'
  resources :authentications
  devise_for :users, :controllers => { :registrations => 'registrations'}
  
  # If logged in will take to org index, otherwise home page
  root :to => "home#index", :constraints => lambda{|req| req.session['warden.user.user.key'].blank?}
  root :to => "org#index", :constraints => lambda{|req| !req.session['warden.user.user.key'].blank?}
  match '/notice' => "home#notice", :as => 'notice'
  
  # Allows for discrete and non-discrete linking to orgs
  match '/:org_id' => 'org#show', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'org_discrete'
  match '/:org_name' => 'org#show', :constraints => lambda{|req| !administrative.include?(req.params[:org_name]) }, :as => 'org'

  # Membership management routes
  match '/:org_id/~/:membership/destroy' => 'memberships#destroy', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'destroy_membership'
  match '/:org_id/~/:membership/update' => 'memberships#update', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'update_membership'
  match '/:org_id/~/invite/create' => 'memberships#add', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'add_membership'
  match '/:org_id/~/invite/:invite_token' => 'memberships#invite', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'invite_membership'

  #List management routes
  match '/:org_id/~/create' => 'lists#create', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'list_create', :via => [:put, :post]
  match '/:org_id/~/new' => 'lists#new', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id]}, :as => 'list_new'

  match '/:org_name/:list_name/update' => 'lists#update', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name]) }, :as => 'list_update', :via => [:put, :post]
  match '/:org_name/:list_name/~edit' => 'lists#edit', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name]) }, :as => 'list_edit'
  match '/:org_name/:list_name/~edit/update' => 'lists#update_list', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name]) }, :as => 'list_admin_update', :via => [:put, :post]
  match '/:org_name/:list_name' => 'lists#show', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name])}, :as => 'list'
  
  #Views with list
  match '/:org_name/:list_name/:view_name' => 'lists#show', :constraints => lambda{|req| !services.include?(req.params[:list_name]) && !administrative.include?(req.params[:org_name])}, :as => 'view'
  match '/:org_id/:list_id/:view_slug' => 'lists#show', :constraints => lambda {|req| /^[-+]?[0-9]+$/ === req.params[:org_id] && /^[-+]?[0-9]+$/ === req.params[:list_id] }, :as => 'view_discrete'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=raw yield(:doc_title)+' | ' unless yield(:doc_title).empty? %>Go. Fight. Win.</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body class="
	<%= 'big_header' unless yield(:extra).empty? %>
	site
	<%= user_signed_in? ? 'authed' : 'inauth' %>
	">

	<% if user_signed_in? %>
	<div id="header">
		<div id="user_nav">
		    <p>you are
			<%= link_to current_user.email, edit_user_registration_path %> | 
		    <%= link_to "sign out", destroy_user_session_path, :method => :delete %>
			</p>
		 </div>
		<% if @list.nil? %>
			<%= link_to 'GFW.', root_url, :id => 'logo' %>
		<% else %>
			<%= link_to 'GFW.', org_path(@org.to_param), :id => 'logo' %>
		<% end %>
		
		<% unless yield(:page_title).empty? %>
			<h1 class="title"><%=h yield(:page_title) %></h1>
		<% end %>
		
		<% if @dsd.nil? %>
			<p style="background-color: #fff;
			width: 220px;
			padding: 6px;
			border-radius: 5px;
			position: absolute;
			<%= 'top: 14px; right: 140px;' unless yield(:extra).empty? %>
			<%= 'top: -4px; right: 340px;' if yield(:extra).empty? %>
			font-size: 7px;"><strong>NOTICE:</strong> <a style="color: #747474" href="<%= notice_path %>" >GFW is no longer in active development</a></p>
		<% end %>
		<%=h yield(:extra) %>
		<div id="msg">
			<div id="container">
				<span class="clear"><%= 'x' if !notice.nil? || !alert.nil? %></span>
				<% unless notice.nil? %>
					<p class="notice"><%= notice %></p>
				<% end %>
				<% unless alert.nil? %>
					<p class="alert"><%= alert %></p>
				<% end %>
			</div>
	    </div>
	</div>
	<% else %>
	<div id="msg">
		<div id="container">
			<span class="clear"><%= 'x' if !notice.nil? || !alert.nil? %></span>
			<p class="notice"><%= notice %></p>
    		<p class="alert"><%= alert %></p>
		</div>
    </div>
	<div id="unauthorized">
		<h1>Go. Fight. Win.</h1>
	<% end %>
		<div id="content">
	<%= yield %>
		</div>
	<% if user_signed_in? %>
	<% else %>
		</div>
	<% end %>
	<div id="overlay">
		<span class="overlay_close clickable">x</span>
		<%= yield(:overlay) %>
	</div>
	<div id="footer">
		<%= yield(:footer) %>
	</div>
	<script type="text/javascript">
		current_user = <%= raw current_user.to_json %>;
	</script>
</body>
</html>